### ISSUE TITLE
RunTime Error : NoClassDefFoundError: org/apache/hadoop/fs/PathId

### ISSUE THREAD

**Issue by alivcor** [mapr-demos/ojai-spark-connector-sample#1]
Hi,

Thanks for the example !

I am running into this run-time error, have verified that my dependencies are correct and up-to-date:

build.sbt:
```
resolvers += "MapR-specific JAR Repository" at "http://repository.mapr.com/maven/"
libraryDependencies += "org.apache.spark" % "spark-core_2.11" % "2.1.0-mapr-1703" 
libraryDependencies += "org.apache.spark" % "spark-sql_2.11" % "2.1.0-mapr-1703" 
libraryDependencies += "com.mapr.db" % "maprdb-spark" % "5.2.1-mapr"
libraryDependencies += "com.mapr.hadoop" % "maprfs" % "5.1.0-mapr"
```

```
[error] (run-main-0) java.lang.NoClassDefFoundError: org/apache/hadoop/fs/PathId
[error] java.lang.NoClassDefFoundError: org/apache/hadoop/fs/PathId
[error]         at com.mapr.db.impl.AdminImpl.newMapRFS(AdminImpl.java:68)
[error]         at com.mapr.db.impl.AdminImpl.<init>(AdminImpl.java:57)
[error]         at com.mapr.db.impl.AdminImpl.<init>(AdminImpl.java:53)
[error]         at com.mapr.db.MapRDB.newAdmin(MapRDB.java:132)
[error]         at com.mapr.db.MapRDB.tableExists(MapRDB.java:50)
[error]         at com.mapr.db.spark.utils.MapRDBUtils$.checkOrCreateTable(MapRDBUtils.scala:23)
[error]         at com.mapr.db.spark.RDD.OJAIDocumentRDDFunctions.saveToMapRDB(DocumentRDDFunctions.scala:36)
[error]         at LineageDemoScala$.main(Main.scala:18)
[error]         at LineageDemoScala.main(Main.scala)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.lang.reflect.Method.invoke(Method.java:498)
[error] Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.fs.PathId
[error]         at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[error]         at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[error]         at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[error]         at com.mapr.db.impl.AdminImpl.newMapRFS(AdminImpl.java:68)
[error]         at com.mapr.db.impl.AdminImpl.<init>(AdminImpl.java:57)
[error]         at com.mapr.db.impl.AdminImpl.<init>(AdminImpl.java:53)
[error]         at com.mapr.db.MapRDB.newAdmin(MapRDB.java:132)
[error]         at com.mapr.db.MapRDB.tableExists(MapRDB.java:50)
[error]         at com.mapr.db.spark.utils.MapRDBUtils$.checkOrCreateTable(MapRDBUtils.scala:23)
[error]         at com.mapr.db.spark.RDD.OJAIDocumentRDDFunctions.saveToMapRDB(DocumentRDDFunctions.scala:36)
[error]         at LineageDemoScala$.main(Main.scala:18)
[error]         at LineageDemoScala.main(Main.scala)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.lang.reflect.Method.invoke(Method.java:498)
18/08/27 21:15:16 ERROR util.Utils: uncaught error in thread SparkListenerBus, stopping SparkContext
java.lang.InterruptedException
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:998)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
        at java.util.concurrent.Semaphore.acquire(Semaphore.java:312)
        at org.apache.spark.scheduler.LiveListenerBus$$anon$1$$anonfun$run$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(LiveListenerBus.scala:80)
        at org.apache.spark.scheduler.LiveListenerBus$$anon$1$$anonfun$run$1$$anonfun$apply$mcV$sp$1.apply(LiveListenerBus.scala:79)
        at org.apache.spark.scheduler.LiveListenerBus$$anon$1$$anonfun$run$1$$anonfun$apply$mcV$sp$1.apply(LiveListenerBus.scala:79)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
        at org.apache.spark.scheduler.LiveListenerBus$$anon$1$$anonfun$run$1.apply$mcV$sp(LiveListenerBus.scala:78)
        at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1245)
        at org.apache.spark.scheduler.LiveListenerBus$$anon$1.run(LiveListenerBus.scala:77)
18/08/27 21:15:16 ERROR util.Utils: throw uncaught fatal error in thread SparkListenerBus
java.lang.InterruptedException
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:998)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
        at java.util.concurrent.Semaphore.acquire(Semaphore.java:312)
        at org.apache.spark.scheduler.LiveListenerBus$$anon$1$$anonfun$run$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(LiveListenerBus.scala:80)
        at org.apache.spark.scheduler.LiveListenerBus$$anon$1$$anonfun$run$1$$anonfun$apply$mcV$sp$1.apply(LiveListenerBus.scala:79)
        at org.apache.spark.scheduler.LiveListenerBus$$anon$1$$anonfun$run$1$$anonfun$apply$mcV$sp$1.apply(LiveListenerBus.scala:79)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
        at org.apache.spark.scheduler.LiveListenerBus$$anon$1$$anonfun$run$1.apply$mcV$sp(LiveListenerBus.scala:78)
        at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1245)
        at org.apache.spark.scheduler.LiveListenerBus$$anon$1.run(LiveListenerBus.scala:77)
18/08/27 21:15:16 INFO server.ServerConnector: Stopped Spark@34d136bc{HTTP/1.1}{0.0.0.0:4041}
18/08/27 21:15:16 INFO handler.ContextHandler: Stopped o.s.j.s.ServletContextHandler@75f44aca{/stages/stage/kill,null,UNAVAILABLE,@Spark}

```

I have two questions here:

1. Which dependency am I missing here?
2. Is it possible to use SparkSQL directly over Spark Thriftserver instead of programmatically accessing MapRDB tables?

Any help is greatly appreciated !

Thanks

**Comment by alivcor** [comment]
Figured out - 


[https://community.mapr.com/thread/18847-mapr-maven-dependency-conflicts-with-existing-hadoop-dependency](https://community.mapr.com/thread/18847-mapr-maven-dependency-conflicts-with-existing-hadoop-dependency)

```
unmanagedJars in Compile += file("/opt/mapr/hadoop/hadoop-2.7.0/share/hadoop/common/hadoop-common-2.7.0-mapr-1707.jar")
unmanagedJars in Compile += file("/opt/mapr/hadoop/hadoop-2.7.0/share/hadoop/common/lib/hadoop-auth-2.7.0-mapr-1707.jar")
```
